# Generated by Django 2.0 on 2018-05-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_buffer_recv',
            name='timestamp',
        ),
    ]
