# Generated by Django 2.0 on 2018-05-20 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_buffer_recv_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_buffer_recv',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
