# Generated by Django 2.0 on 2018-05-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20180521_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_data',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='user',
        ),
        migrations.RenameField(
            model_name='client_buffer_recv',
            old_name='buffer_data',
            new_name='data',
        ),
        migrations.DeleteModel(
            name='Client_data',
        ),
        migrations.DeleteModel(
            name='meta',
        ),
    ]
