# Generated by Django 2.0 on 2018-06-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20180611_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='patient',
        ),
    ]
