# Generated by Django 2.0 on 2018-06-11 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0008_client_buffer_recv_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Patient_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='patient',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='clients.Patient'),
            preserve_default=False,
        ),
    ]
